export default {
    attention_seekers: [
        'shakeX',
        'shakeY',
        'bounce',
        'flash',
        'headShake',
        'heartBeat',
        // 'jello',
        'pulse',
        'rubberBand',
        'shake',
        'swing',
        'tada',
        'wobble',
    ],
    bouncing_exits: ['bounceOut', 'bounceOutDown', 'bounceOutLeft', 'bounceOutRight', 'bounceOutUp'],
    bouncing_entrances: ['bounceIn', 'bounceInDown', 'bounceInLeft', 'bounceInRight', 'bounceInUp'],
    fading_entrances: [
        'fadeIn',
        'fadeInDown',
        'fadeInDownBig',
        'fadeInLeft',
        'fadeInLeftBig',
        'fadeInRight',
        'fadeInRightBig',
        'fadeInUp',
        'fadeInUpBig',
    ],
    fading_exits: [
        'fadeOut',
        'fadeOutDown',
        'fadeOutDownBig',
        'fadeOutLeft',
        'fadeOutLeftBig',
        'fadeOutRight',
        'fadeOutRightBig',
        'fadeOutUp',
        'fadeOutUpBig',
    ],
    // flippers: ['flip', 'flipInX', 'flipInY', 'flipOutX', 'flipOutY'],
    // lightspeed: ['lightSpeedIn', 'lightSpeedOut'],
    rotating_entrances: ['rotateIn', 'rotateInDownLeft', 'rotateInDownRight', 'rotateInUpLeft', 'rotateInUpRight'],
    sliding_entrances: ['slideInDown', 'slideInLeft', 'slideInRight', 'slideInUp'],
    sliding_exits: ['slideOutDown', 'slideOutLeft', 'slideOutRight', 'slideOutUp'],
    specials: [
        'hinge',
        // 'jackInTheBox',
        'rollIn',
        'rollOut',
    ],
    zooming_entrances: ['zoomIn', 'zoomInDown', 'zoomInLeft', 'zoomInRight', 'zoomInUp'],
    rotating_exits: ['rotateOut', 'rotateOutDownLeft', 'rotateOutDownRight', 'rotateOutUpLeft', 'rotateOutUpRight'],
    zooming_exits: ['zoomOut', 'zoomOutDown', 'zoomOutLeft', 'zoomOutRight', 'zoomOutUp'],
};
